# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ba96e4f120e84d10e215f34a97a56c337278659137b4ad96b758ea8fdf3c381fa3b039bfb33ef8f6c1628b4dcd91c682cce0c5f8ea65a4569a5f5c237fc4c9

test:
  secret_key_base: 602867601b56f29bb6bbfc4126249ee48229ec6eb8b10063ab68f4b04e3c87631600ee1db2c80758bc2908641cc1d11a22d80dc61ef0b9621cc8efa0443965c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
